on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up repo
        run: |
          unzip default_initramfs.zip -d .
          cp defaults.json config.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Build
        run: |
          npm ci
          npm run build
          echo BUILD=$(cat .osbuild) >> $GITHUB_OUTPUT
        id: build

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: dist/*
          body: New pre-built Amethyst version
          prerelease: true
          tag_name: amt-${{ steps.build.outputs.BUILD }}
          name: Build ${{ steps.build.outputs.BUILD }}
