on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
      - uses: actions/checkout@v6
      - run: unzip default_initramfs.zip -d .
      - run: cp defaults.json
      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - run: npm install
      - run: npm run build

      - uses: softprops/action-gh-release@v3
      - name: Release
      - with:
          files: dist/*
